png<?php
namespace Teamwork\Tasks;

class Memory {

  private $memoryTests = [

    'faces_1' => [
        'test_name' => 'faces_1',
        'task_type' => 'images',
        'directory' => '/img/memory-task/faces/',
        'blocks' => [
          ['type' => 'practice_review',
          'text' => 'We\'ll start with a practice. Look at these 6 faces for a few seconds. We\'ll call these
                    "target faces".',
          'targets' => ['p0_targets_1.png'],
          'review_time' => null],
        [ 'type' => 'practice_test',
          'selection_type' => 'select_one',
          'prompt' => 'Which of the following faces is a "target" face?',
          'img' => 'p0_test_1.png',
          'correct' => [1]],
        [ 'type' => 'practice_test',
          'selection_type' => 'select_one',
          'prompt' => 'Which of the following faces is a "target" face?',
          'img' => 'p0_test_2.png',
          'correct' => [3]],
        ['type' => 'text',
          'text' => 'When you click "Continue" a screen will appear with 6 target
                     faces. You can view the faces front-on or with the heads
                     turned to one side. You will have 20 seconds to memorize
                     these target faces.',
        ],
        ['type' => 'review',
          'text' => '',
          'targets' => ['1_targets_1.png', '1_targets_2.png', '1_targets_3.jpg'],
          'review_time' => 20,],
          [ 'type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_1.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_2.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_3.jpg',
            'correct' => [1]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_4.jpg',
            'correct' => [1]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_5.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_6.jpg',
            'correct' => [2]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_7.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_8.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_9.jpg',
            'correct' => [1]],

          ['type' => 'review',
            'text' => 'Here’s a reminder of the faces.
            You have 10 seconds to refresh your memory.',
            'targets' => ['1_targets_1.png', '1_targets_2.png', '1_targets_3.jpg'],
            'review_time' => 10,
          ],

          ['type' => 'text',
            'text' => 'For the last six questions, some
            of the images are deliberately blurred to make
            things more challenging.',
          ],

          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_10.jpg',
            'correct' => [1]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_11.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following faces is a "target" face?',
            'img' => '1_test_12.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_13.jpg',
            'correct' => [2]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_14.jpg',
            'correct' => [1]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '1_test_15.jpg',
            'correct' => [2]],

          ], // End blocks

    ], // End faces_1

    'faces_2' => [
        'test_name' => 'faces_2',
        'task_type' => 'images',
        'directory' => '/img/memory-task/faces/',
        'blocks' => [
          ['type' => 'practice_review',
          'text' => 'We\'ll start with a practice. Look at these 6 faces for a few seconds. We\'ll call these
                    "target faces".',
          'targets' => ['p0_targets_1.png'],
          'review_time' => null],
        [ 'type' => 'practice_test',
          'selection_type' => 'select_one',
          'prompt' => 'Which of the following faces is a "target" face?',
          'img' => 'p0_test_1.png',
          'correct' => [1]],
        [ 'type' => 'practice_test',
          'selection_type' => 'select_one',
          'prompt' => 'Which of the following faces is a "target" face?',
          'img' => 'p0_test_2.png',
          'correct' => [3]],
        ['type' => 'text',
          'text' => 'When you click "Continue" a screen will appear with 6 target
                     faces. You can view the faces front-on or with the heads
                     turned to one side. You will have 20 seconds to memorize
                     these target faces.',
        ],
        ['type' => 'review',
          'text' => '',
          'targets' => ['2_targets_1.jpg', '2_targets_2.jpg', '2_targets_3.jpg'],
          'review_time' => 20,],
          [ 'type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '2_test_1.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '2_test_2.jpg',
            'correct' => [1]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '2_test_3.jpg',
            'correct' => [2]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '2_test_4.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '2_test_5.jpg',
            'correct' => [1]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '2_test_6.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '2_test_7.jpg',
            'correct' => [2]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" face?',
            'img' => '2_test_8.jpg',
            'correct' => [2]],
          ], // End blocks

    ], // End faces_2

    'cars_1' => [
        'test_name' => 'cars_1',
        'task_type' => 'images',
        'directory' => '/img/memory-task/cars/',
        'blocks' => [
          ['type' => 'practice_review',
          'text' => 'We\'ll start with a practice. Look at these 6 faces for a few seconds. We\'ll call these
                    "target faces".',
          'targets' => ['p0_targets_1.png'],
          'review_time' => null],
        [ 'type' => 'practice_test',
          'selection_type' => 'select_one',
          'prompt' => 'Which of the following faces is a "target" face?',
          'img' => 'p0_test_1.png',
          'correct' => [1]],
        [ 'type' => 'practice_test',
          'selection_type' => 'select_one',
          'prompt' => 'Which of the following faces is a "target" face?',
          'img' => 'p0_test_2.png',
          'correct' => [3]],
        ['type' => 'text',
          'text' => 'Now for the actual task. In the task you’ll try to remember cars, not faces.
                     On the next screen, you will review 6 target cars for 20 seconds.
                    You can see them front-on, or in profile. Click the "change perspective" button to see the cars from a different angle.
                    Try to remember all 6 cars.
                    Your time will start when you click "Continue".',
        ],
        ['type' => 'review',
          'text' => '',
          'targets' => ['1_targets_1.png', '1_targets_2.png', '1_targets_3.png'],
          'review_time' => 20,],
          [ 'type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'false',
            'prompt' => 'Which of the following images is a "target" car?',
            'img' => '1_test_1.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'false',
            'prompt' => 'Which of the following images is a "target" car?',
            'img' => '1_test_2.jpg',
            'correct' => [1]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'false',
            'prompt' => 'Which of the following images is a "target" car?',
            'img' => '1_test_3.jpg',
            'correct' => [1]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'false',
            'prompt' => 'Which of the following images is a "target" car?',
            'img' => '1_test_4.jpg',
            'correct' => [2]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'false',
            'prompt' => 'Which of the following images is a "target" car?',
            'img' => '1_test_5.jpg',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'false',
            'prompt' => 'Which of the following images is a "target" car?',
            'img' => '1_test_6.jpg',
            'correct' => [2]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'false',
            'prompt' => 'Which of the following images is a "target" car?',
            'img' => '1_test_7.jpg',
            'correct' => [2]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'false',
            'prompt' => 'Which of the following images is a "target" car?',
            'img' => '1_test_8.jpg',
            'correct' => [3]],
          ], // End blocks

    ], // End cars_1

    'bikes_1' => [
        'test_name' => 'bikes_1',
        'task_type' => 'images',
        'directory' => '/img/memory-task/bikes/',
        'blocks' => [
          ['type' => 'practice_review',
          'text' => 'We\'ll start with a practice. Look at these 6 faces for a few seconds. We\'ll call these
                    "target faces".',
          'targets' => ['p0_targets_1.png'],
          'review_time' => null],
        [ 'type' => 'practice_test',
          'selection_type' => 'select_one',
          'prompt' => 'Which of the following faces is a "target" face?',
          'img' => 'p0_test_1.png',
          'correct' => [1]],
        [ 'type' => 'practice_test',
          'selection_type' => 'select_one',
          'prompt' => 'Which of the following faces is a "target" face?',
          'img' => 'p0_test_2.png',
          'correct' => [3]],
        ['type' => 'text',
          'text' => 'Now for the actual task. In the task you’ll try to remember bicycles, not faces.
                     On the next screen, you will review 6 target bicycles for 20 seconds.
                    You can see them front-on, or in profile. Click the "change perspective" button to see the bicycles from a different angle.
                    Try to remember all 6 bicycles.
                    Your time will start when you click "Continue".',
        ],
        ['type' => 'review',
          'text' => '',
          'targets' => ['2_targets_1.png', '2_targets_2.png', '2_targets_3.png'],
          'review_time' => 20,],
          [ 'type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" bicycle?',
            'img' => '2_test_1.png',
            'correct' => [1]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" bicycle?',
            'img' => '2_test_2.png',
            'correct' => [2]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" bicycle?',
            'img' => '2_test_3.png',
            'correct' => [1]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" bicycle?',
            'img' => '2_test_4.png',
            'correct' => [2]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" bicycle?',
            'img' => '2_test_5.png',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" bicycle?',
            'img' => '2_test_6.png',
            'correct' => [3]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" bicycle?',
            'img' => '2_test_7.png',
            'correct' => [2]],
          ['type' => 'test',
            'selection_type' => 'select_one',
            'show_numbers' => 'true',
            'prompt' => 'Which of the following images is a "target" bicycle?',
            'img' => '2_test_8.png',
            'correct' => [3]],
          ], // End blocks

    ], // End bikes_1

    'words_1' => [
          'test_name' => 'words_1',
          'task_type' => 'words',
          'blocks' => [
              ['type' => 'text',
               'text' => 'Next, we’ll test word memory. In this task,
                        you’ll be presented with a set of "target words".  Each word
                        will show up separately for 2 seconds. We’ll start
                        with a practice. In the practice round, you only have
                        to remember 3 target words.',],
              ['type' => 'review',
              'text' => '',
              'targets' => ['blue', 'yellow', 'red'],
              'review_time_each' => 2,
              'review_time' => null],
              [ 'type' => 'practice_test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words?',
                'choices' => ['red', 'rust', 'blue'],
                'correct' => [1, 3]],
              [ 'type' => 'practice_test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words?',
                'choices' => ['green', 'baseball', 'egg'],
                'correct' => [],
                'popup_text' => 'Sometimes, none of the words will be a target word.<br>In that case, just click "next"!',
                'popup_display_time' => 5],
              ['type' => 'text',
              'text' => 'Now for the actual task. You will be presented with 12 target
                          words. Try to remember all of them. Each word will
                          show up separately for 2 seconds.
                          You’re not allowed to write anything down. The words will
                          begin to appear when you click "Continue".',],
              ['type' => 'review',
              'text' => '',
              'targets' => ['horse', 'cave', 'lion', 'opal', 'tiger',
                          'pearl', 'hut', 'emerald', 'sapphire',
                          'tent', 'hotel', 'cow'],
              'review_time_each' => 2,
              'review_time' => null],
              ['type' => 'test',
               'selection_type' => 'select_all',
               'prompt' => 'Which of the following are target words',
               'choices' => ['house', 'tiger', 'hut'],
               'correct' => [2, 3]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['hotel', 'coffee', 'mountain'],
                'correct' => [1]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['cow', 'dog', 'emerald'],
                'correct' => [1, 3]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['ruby', 'pig', 'balloon'],
                'correct' => []],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['apartment', 'tiger', 'diamond'],
                'correct' => [2]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['pearl', 'scarf', 'hotel'],
                'correct' => [1, 3]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['boat', 'penny', 'cat'],
                'correct' => []],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['lion', 'sapphire', 'cave'],
                'correct' => [1, 2, 3]],


          ] // End blocks

    ], // End words_1

    'words_2' => [
          'test_name' => 'words_2',
          'task_type' => 'words',
          'blocks' => [
              ['type' => 'text',
               'text' => 'Next, we’ll test word memory. In this task,
                        you’ll be presented with a set of "target words".  Each word
                        will show up separately for 2 seconds. We’ll start
                        with a practice. In the practice round, you only have
                        to remember 3 target words.',],
              ['type' => 'review',
              'text' => '',
              'targets' => ['blue', 'yellow', 'red'],
              'review_time_each' => 2,
              'review_time' => null],
              [ 'type' => 'practice_test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words?',
                'choices' => ['red', 'rust', 'blue'],
                'correct' => [1, 3]],
              [ 'type' => 'practice_test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words?',
                'choices' => ['green', 'baseball', 'egg'],
                'correct' => [],
                'popup_text' => 'Sometimes, none of the words will be a target word.<br>In that case, just click "next"!',
                'popup_display_time' => 5],
              ['type' => 'text',
              'text' => 'Now for the actual task. You will be presented with 12 target
                          words. Try to remember all of them. Each word will
                          show up separately for 2 seconds.
                          You’re not allowed to write anything down. The words will
                          begin to appear when you click "Continue".',],
              ['type' => 'review',
              'text' => '',
              'targets' => ['pistol', 'fork', 'pot', 'sword', 'vodka',
                          'rum', 'bomb', 'pan', 'wine',
                          'spatula', 'bourbon', 'rifle'],
              'review_time_each' => 2,
              'review_time' => null],
              ['type' => 'test',
               'selection_type' => 'select_all',
               'prompt' => 'Which of the following are target words',
               'choices' => ['fork', 'pan', 'knife'],
               'correct' => [1, 2]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['spatula', 'beer', 'bomb'],
                'correct' => [1, 3]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['whiskey', 'lemon', 'gun'],
                'correct' => []],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['gun', 'pistol', 'trout'],
                'correct' => [2]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['wine', 'fork', 'sword'],
                'correct' => [1, 2, 3]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['rum', 'pencil', 'pot'],
                'correct' => [1, 3]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['can', 'vodka', 'spoon'],
                'correct' => [2]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['rifle', 'gold', 'strainer'],
                'correct' => [1]],


          ] // End blocks

    ], // End words_2

    'words_3' => [
          'test_name' => 'words_3',
          'task_type' => 'words',
          'blocks' => [
              ['type' => 'text',
               'text' => 'Next, we’ll test word memory. In this task,
                        you’ll be presented with a set of "target words".  Each word
                        will show up separately for 2 seconds. We’ll start
                        with a practice. In the practice round, you only have
                        to remember 3 target words.',],
              ['type' => 'review',
              'text' => '',
              'targets' => ['blue', 'yellow', 'red'],
              'review_time_each' => 2,
              'review_time' => null],
              [ 'type' => 'practice_test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words?',
                'choices' => ['red', 'rust', 'blue'],
                'correct' => [1, 3]],
              [ 'type' => 'practice_test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words?',
                'choices' => ['green', 'baseball', 'egg'],
                'correct' => [],
                'popup_text' => 'Sometimes, none of the words will be a target word.<br>In that case, just click "next"!',
                'popup_display_time' => 5],
              ['type' => 'text',
              'text' => 'Now for the actual task. You will be presented with 12 target
                          words. Try to remember all of them. Each word will
                          show up separately for 2 seconds.
                          You’re not allowed to write anything down. The words will
                          begin to appear when you click "Continue".',],
              ['type' => 'review',
              'text' => '',
              'targets' => ['garlic', 'wood', 'sugar', 'coal', 'clarinet',
                            'trumpet', 'cinnamon', 'flute', 'kerosine',
                            'vanilla', 'gasoline', 'violin'],
              'review_time_each' => 2,
              'review_time' => null],
              ['type' => 'test',
               'selection_type' => 'select_all',
               'prompt' => 'Which of the following are target words',
               'choices' => ['oil', 'kerosine', 'priest'],
               'correct' => [2]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['salt', 'basement', 'piano'],
                'correct' => []],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['wood', 'harmonica', 'trumpet'],
                'correct' => [1, 3]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['flute', 'clarinet', 'piano'],
                'correct' => [2]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['garlic', 'violin', 'vanilla'],
                'correct' => [1, 2, 3]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['chair', 'pepper', 'horn'],
                'correct' => []],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['sand', 'sugar', 'drum'],
                'correct' => [2]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['coal', 'electricity', 'lemon'],
                'correct' => [1]],


          ] // End blocks

    ], // End words_3

    'words_4' => [
          'test_name' => 'words_4',
          'task_type' => 'words',
          'blocks' => [
              ['type' => 'text',
               'text' => 'Next, we’ll test word memory. In this task,
                        you’ll be presented with a set of "target words".  Each word
                        will show up separately for 2 seconds. We’ll start
                        with a practice. In the practice round, you only have
                        to remember 3 target words.',],
              ['type' => 'review',
              'text' => '',
              'targets' => ['blue', 'yellow', 'red'],
              'review_time_each' => 2,
              'review_time' => null],
              [ 'type' => 'practice_test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words?',
                'choices' => ['red', 'rust', 'blue'],
                'correct' => [1, 3]],
              [ 'type' => 'practice_test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words?',
                'choices' => ['green', 'baseball', 'egg'],
                'correct' => [],
                'popup_text' => 'Sometimes, none of the words will be a target word.<br>In that case, just click "next"!',
                'popup_display_time' => 5],
              ['type' => 'text',
              'text' => 'Now for the actual task. You will be presented with 12 target
                          words. Try to remember all of them. Each word will
                          show up separately for 2 seconds.
                          You’re not allowed to write anything down. The words will
                          begin to appear when you click "Continue".',],
              ['type' => 'review',
              'text' => '',
              'targets' => ['bluebird', 'chisel', 'eagle', 'screwdriver', 'crow',
                            'wrench', 'pants', 'nails', 'shoes',
                            'canary', 'skirt', 'blouse'],
              'review_time_each' => 2,
              'review_time' => null],
              ['type' => 'test',
               'selection_type' => 'select_all',
               'prompt' => 'Which of the following are target words',
               'choices' => ['child', 'bluebird', 'chapel'],
               'correct' => [2]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['canary', 'socks', 'robin'],
                'correct' => [1]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['hammer', 'skirt', 'apple'],
                'correct' => [2]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['shirt', 'saw', 'wren'],
                'correct' => []],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['chisel', 'screwdriver', 'sparrow'],
                'correct' => [1, 2]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['silver', 'nails', 'eagle'],
                'correct' => [2, 3]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['crow', 'rock', 'rook'],
                'correct' => [1]],
              ['type' => 'test',
                'selection_type' => 'select_all',
                'prompt' => 'Which of the following are target words',
                'choices' => ['blouse', 'pants', 'wrench'],
                'correct' => [1, 2, 3]],


          ] // End blocks

    ], // End words_4

    'story_1' => [
        'test_name' => 'story_1',
        'task_type' => 'story',
        'directory' => '/img/memory-task/faces/',
        'blocks' => [
            ['type' => 'text',
             'text' => 'The last memory task asks you to remember
                             two very short stories. Once again, we’ll start with a
                             practice. In the practice round, you only have to
                             remember one sentence.'],
            ['type' => 'review',
            'text' => 'Practice story:',
            'targets' => ['Peter was hungry, so he went to the store on the
                            corner of his street and bought a hamburger.'],
            'review_time' => 15],
            [ 'type' => 'practice_test',
              'selection_type' => 'select_one',
              'prompt' => 'Why did Peter go to the store?',
              'choices' => ['Because he was hungry',
                            'To get coffee',
                            'To buy food for his dog'],
              'correct' => [1]],
            [ 'type' => 'practice_test',
              'selection_type' => 'select_one',
              'prompt' => 'What did Peter eat?',
              'choices' => ['Hamburger',
                            'Sandwich',
                            'Fries'],
              'correct' => [1]],
            ['type' => 'text',
             'text' => 'Now for the actual task. You will be
                         presented with a slightly longer story. You
                         will have 30 seconds to read it. Try to take
                         in as much information as possible. After the 30
                         seconds are up, we’ll ask you some questions
                         about the story. Again, you&#39;re not allowed to
                         write anything down. The story will
                         appear when you click "Continue".'],
            ['type' => 'review',
            'text' => '',
            'targets' => ['Anna Thompson of South Boston, employed
                            as a cook in a school cafeteria, reported at the
                            police station that she had been held up on State
                            Street the night before and robbed of $56. She had
                            four small children, the rent was due, and they had
                            not eaten for two days. The police, touched by the
                            woman’s story, collected money for her.',],
            'review_time' => 30],

            [ 'type' => 'test',
              'selection_type' => 'select_one',
              'prompt' => 'What was the name of the main character?',
              'choices' => ['Anna Thompson',
                            'Anna Tompkins',
                            'Hanna Tompkins'],
              'correct' => [1]],
            [ 'type' => 'test',
              'selection_type' => 'select_one',
              'prompt' => 'How many children did she have?',
              'choices' => ['4',
                            '5',
                            '6'],
              'correct' => [1]],
            [ 'type' => 'test',
              'selection_type' => 'select_one',
              'prompt' => 'On what street was she robbed?',
              'choices' => ['South Street',
                            'State Street',
                            'Sixth Street'],
                'correct' => [2]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'What was her job?',
                'choices' => ['Cook',
                              'She didn\'t have a job',
                              'Janitor'],
                'correct' => [1]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'When did she report being robbed?',
                'choices' => ['One night after the robbery',
                              'Two nights after the robbery',
                              'A week after the robbery'],
                'correct' => [1]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'How much money was stolen?',
                'choices' => ['$65',
                              '$56',
                              '$66'],
                'correct' => [2]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'How long had the family not eaten for?',
                'choices' => ['2 days',
                              '1 day',
                              'They missed 2 meals'],
                'correct' => [1]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'What did the police do?',
                'choices' => ['Arrest the thief',
                              'Collect money for the woman',
                              'Give the woman food'],
                'correct' => [2]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'Where does the main character live?',
                'choices' => ['South Boston',
                              'Somerville',
                              'North Boston'],
                'correct' => [1]]

        ] // End blocks
    ], // End story_1

    'story_2' => [
        'test_name' => 'story_2',
        'task_type' => 'story',
        'blocks' => [
            ['type' => 'text',
             'text' => 'The last memory task asks you to remember
                             a very short story. Once again, we’ll start with a
                             practice. In the practice round, you only have to
                             remember one sentence.'],
            ['type' => 'review',
            'text' => 'Practice story:',
            'targets' => ['Peter was hungry, so he went to the store on the
                            corner of his street and bought a hamburger.'],
            'review_time' => 15],
            [ 'type' => 'practice_test',
              'selection_type' => 'select_one',
              'prompt' => 'Why did Peter go to the store?',
              'choices' => ['Because he was hungry',
                            'To get coffee',
                            'To buy food for his dog'],
              'correct' => [1]],
            [ 'type' => 'practice_test',
              'selection_type' => 'select_one',
              'prompt' => 'What did Peter eat?',
              'choices' => ['Hamburger',
                            'Sandwich',
                            'Fries'],
              'correct' => [1]],
            ['type' => 'text',
             'text' => 'Now for the actual task. You will be
                         presented with a slightly longer story. You
                         will have 30 seconds to read it. Try to take
                         in as much information as possible. After the 30
                         seconds are up, we’ll ask you some questions
                         about the story. Again, you&#39;re not allowed to
                         write anything down. The story will
                         appear when you click "Continue".'],
            ['type' => 'review',
            'text' => '',
            'targets' => ['Anna Thompson of South Boston, employed
                            as a cook in a school cafeteria, reported at the
                            police station that she had been held up on State
                            Street the night before and robbed of $56. She had
                            four small children, the rent was due, and they had
                            not eaten for two days. The police, touched by the
                            woman’s story, collected money for her.',],
            'review_time' => 30],

            [ 'type' => 'test',
              'selection_type' => 'select_one',
              'prompt' => 'What was the name of the main character?',
              'choices' => ['Anna Thompson',
                            'Anna Tompkins',
                            'Hanna Tompkins'],
              'correct' => [1]],
            [ 'type' => 'test',
              'selection_type' => 'select_one',
              'prompt' => 'How many children did she have?',
              'choices' => ['4',
                            '5',
                            '6'],
              'correct' => [1]],
            [ 'type' => 'test',
              'selection_type' => 'select_one',
              'prompt' => 'On what street was she robbed?',
              'choices' => ['South Street',
                            'State Street',
                            'Sixth Street'],
                'correct' => [2]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'What was her job?',
                'choices' => ['Cook',
                              'She didn\'t have a job',
                              'Janitor'],
                'correct' => [1]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'When did she report being robbed?',
                'choices' => ['One night after the robbery',
                              'Two nights after the robbery',
                              'A week after the robbery'],
                'correct' => [1]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'How much money was stolen?',
                'choices' => ['$65',
                              '$56',
                              '$66'],
                'correct' => [2]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'How long had the family not eaten for?',
                'choices' => ['2 days',
                              '1 day',
                              'They missed 2 meals'],
                'correct' => [1]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'What did the police do?',
                'choices' => ['Arrest the thief',
                              'Collect money for the woman',
                              'Give the woman food'],
                'correct' => [2]],
              [ 'type' => 'test',
                'selection_type' => 'select_one',
                'prompt' => 'Where does the main character live?',
                'choices' => ['South Boston',
                              'Somerville',
                              'North Boston'],
                'correct' => [1]]

        ] // End blocks
    ], // End story_2

  ]; // End memoryTests


  private static $avaialbleParams = ['hasIndividuals' => ['true', 'false'], 'hasGroup' => ['true', 'false'],
                                     'test' => ['allows_multiples' => ['faces_1', 'words_1', 'story_1']]];

  public function getTests() {
    return $this->prompts;
  }

  public function setTests($tests) {
    $this->memoryTests = $tests;
  }

  public function getRandomTest() {
    return $this->memoryTests[array_rand($this->memoryTests)];
  }

  public function getTest($test) {
    return $this->memoryTests[$test];
  }


  public static function getAvailableParams()
  {
    return Self::$avaialbleParams;
  }

}
